version: '3.8'

services:
  # Base de Datos Persistente (SQL)
  postgres_db:
    image: postgres:15-alpine
    container_name: fall_detection_pg
    restart: "no"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
      POSTGRES_DB: ${POSTGRES_DB:-fall_detection_pg}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      
      # En Fedora a√±adir ":Z" al final de cada ruta, para que (SELinux) no bloquee el acceso
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:Z
      - ./database/pg_data:/var/lib/postgresql/data:Z
      

  # Base de Datos en Tiempo Real (NoSQL)
  redis_cache:
    image: redis:7-alpine
    container_name: fall_detection_redis
    restart: "no"
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  pg_data: